### ISSUE TITLE
Players losing their inventory

### ISSUE THREAD

**Issue by Sikatsu** [Gnat008/PerWorldInventory#185]
Hey,

Sometimes when a player goes in creative and back in survival, his survival inventory is replaced by the creative inventory. This can also happen the other way around, where their survival inventory is in creative.

I have a survival world and a creative world. So they switch from world when this occurs. This didn't happen on 1.9.0, only on 1.9.1. I'm using 1.11.2 and multiverse.

**Comment by thenameisKO** [comment]
I have recently experienced the same issue; two players reported keeping their creative inventory upon warping from our Creative world to the Overworld, while their survival inventories were gone entirely.  Multiple teleports back and forth as well as re-logging did not solve this, no errors in the console either.

**Comment by Gnat008** [comment]
Could you enable debugging in the plugin config, reproduce the issue, and
give me your server log? Also your worlds.yml config.

**Comment by thenameisKO** [comment]
Might take a little while to see if the issue reproduces itself, but sure thing.

**Comment by Sikatsu** [comment]
Reproducing is quite hard as it happens randomly.

**Comment by Gnat008** [comment]
I think this (or a similar issue) finally decided to show itself on my server out of the blue. I should have it fixed in PR #189.

**Comment by Sikatsu** [comment]
@Gnat008 

Thanks, it still happens that sometimes they take their survival inventory with them in the creative world and the other way around. Not that much, but it happens. You say you fixed it in PR #189 , I would like to test this build but I don't see a download?

**Comment by Sikatsu** [comment]
@Gnat008

**Comment by thenameisKO** [comment]
At this point, these are the encountered glitches I've had reports of:
-Warping out of MobArena (which requires an empty inventory to join; arenas are also in The End) causes the player to have their creative inventory from a few weeks previously
-Warping from creative world to survival causes creative inventory to stay put and survival inventory to be wiped (does not happen other way around)
-Warping from End to Overworld causes survival inventory + enderchest to be wiped
Gamemodes act as they should between warps; only inventories are affected.

Literally the only thing going untouched is AlphaChest as far as inventories go (so at least that isn't interfering at all).

**Comment by Gnat008** [comment]
Update has been released on Spigot.

**Comment by plasticblues** [comment]
This is still occuring we just had one of my staffs inventory cleared when they were testing this with me. I also had this happen, I've taken it off of my server for now but I will make a test server to debug this tomorrow.

**Comment by plasticblues** [comment]
Alright so here is my log:
https://pastebin.com/vY2YzQ73

To reproduce this issue from what I've been able to do on my test server:
Give yourself one stone or whatever item
Switch to creative mode in a world that is survival and set to force game mode
Log out
Log In
You will be forced to survival, your one stone or whatever item will not be in your inventory switching between game modes from creative and back does not bring the item back. This also goes for ender chest, your ender chest will be cleared.

I'm not sure if this is the exact same bug but it is the one I am experiencing, I was also having the issue described above where sometimes inventories didn't when switching between game modes on my production server.
